version: '3.3'
services:

  # The federator service
  federator:
    image: eida-federator:1.0 
    restart: always
    volumes:
      - type: volume
        source: mediatorws_log
        target: /var/www/mediatorws/log
        volume:
          nocopy: false
      - type: volume
        source: mediatorws_tmp
        target: /var/tmp
        volume:
          nocopy: false
      - type: volume
        source: stationlite_data
        target: /var/www/mediatorws/db
        volume:
          nocopy: false
    ports:
      - "8080:80"

  # For the stationlite psql database
  psql:
    image: postgres:11
    restart: always
    volumes:
      - /var/db/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mediatorws_log:
  mediatorws_tmp:
  stationlite_data:
